import { TYPE_UNDEFINED } from './99-types'

export const DEFAULT_VALUE_OPTIONS_NAME = TYPE_UNDEFINED
export const DEFAULT_VALUE_OPTIONS_LIFECYCLE = TYPE_UNDEFINED
export const DEFAULT_VALUE_OPTIONS_VISIBILITY = '`StateManagerVisibility.ENVIRONMENT`'
export const DEFAULT_VALUE_OPTIONS_SUSPENSE = '`false`'
